### ISSUE TITLE
Clarify lobid URIs

### ISSUE THREAD

**Issue by nichtich** [dini-ag-kim/library-data-in-rdf#3]
In <http://lobid.org/resources/990186583900206441.json> the URI in field `id` is `http://lobid.org/resources/990186583900206441#!` instead of expected <http://lobid.org/resources/990186583900206441>. Is this intention?

**Comment by acka47** [comment]
Yes, it is: the hash bang URI stands for the bibliographic resource and the URI without hashbang for the bibliographic description/record, see also https://wiki.dnb.de/display/DINIAGKIM/URI-Design-Empfehlungen .
